apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app
spec:
  type: LoadBalancer
  selector:
    app: register-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
